### ISSUE TITLE
deps/uthash is not troydhanson/uthash 2.0.1

### ISSUE THREAD

**Issue by jirutka** [gjtorikian/mtex2MML#59]
I wanted to unbundle uthash, i.e. compile mtex2MML with [uthash](https://github.com/troydhanson/uthash) from upstream. Unfortunately mtex2MML segfaults when compiled with uthash 2.0.2.

Then I found out that your copy of uthash is **not** uthash 2.0.1, despite the UTHASH_VERSION and information in package.json! It’d be fair to at least warn about this in README.

**Comment by gjtorikian** [comment]
Blaugh! Sorry about that. I'll look into it!
