### ISSUE TITLE
most recent release build fails due to C23 function prototype requirement

### ISSUE THREAD

**Issue by nathan-contino** [gjtorikian/mtex2MML#76]
Version 1.3.1 of this library no longer builds with C23 compilers due to the following error:

```
A function declaration without a prototype is deprecated in all versions of C [-Werror, -Wstrict-prototypes]
```

(See 'old-style function declarations and definitions' in the [C23 spec](https://en.cppreference.com/w/c/23))

It looks like [PR 75](https://github.com/gjtorikian/mtex2MML/pull/75) fixed this issue. However, I can't find a release that includes this change, so I get an error when I try to install libraries that depend upon this one (such as [mathematical](https://github.com/gjtorikian/mathematical)). I've managed to build and install this library manually, so I can confirm that the fix works. But that isn't the most sustainable model for my toolchain 😄 

Can you cut a release (1.3.2, perhaps?) that includes the function prototype fix? Thank you.

**Comment by aallan** [comment]
This is a serious issue and leaves a bunch of upchain software that relies on this library unable to build on macOS without a lot of manual intervention which is going to be awfully brittle in managed environments. A new release with the #75 fix incorporated would be much appreciated!

**Comment by gjtorikian** [comment]
Ok, v1.3.2 is out now: https://github.com/gjtorikian/mtex2MML/releases/tag/v1.3.2

I don't really monitor this repo or mathematical as often as I should. I don't know how important or useful this project is. If anyone would like collaboration access I'd be happy to grant it.

**Comment by nathan-contino** [comment]
@gjtorikian, I would be happy to accept collaboration access on mtex2MML and mathematical. That way we'll have a bit more redundancy if issues arise with this in the future.

**Comment by gjtorikian** [comment]
granted, have fun!
